/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/(auth)/login': RouteRecordInfo<
      '/(auth)/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(auth)/signup': RouteRecordInfo<
      '/(auth)/signup',
      '/signup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(home)': RouteRecordInfo<
      '/(home)',
      '/',
      Record<never, never>,
      Record<never, never>,
      | '/(home)/'
      | '/(home)/calendar'
      | '/(home)/me'
    >,
    '/(home)/': RouteRecordInfo<
      '/(home)/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(home)/calendar': RouteRecordInfo<
      '/(home)/calendar',
      '/calendar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(home)/me': RouteRecordInfo<
      '/(home)/me',
      '/me',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/(auth)/login.vue': {
      routes:
        | '/(auth)/login'
      views:
        | never
    }
    'src/pages/(auth)/signup.vue': {
      routes:
        | '/(auth)/signup'
      views:
        | never
    }
    'src/pages/(home).vue': {
      routes:
        | '/(home)'
        | '/(home)/'
        | '/(home)/calendar'
        | '/(home)/me'
      views:
        | 'default'
    }
    'src/pages/(home)/index.vue': {
      routes:
        | '/(home)/'
      views:
        | never
    }
    'src/pages/(home)/calendar.vue': {
      routes:
        | '/(home)/calendar'
      views:
        | never
    }
    'src/pages/(home)/me.vue': {
      routes:
        | '/(home)/me'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
